format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$jobs\
$character\
"""

[directory]
read_only = " "
truncate_to_repo = false

[git_branch]
symbol = " "

[hostname]
disabled = false

[python]
format = "[$virtualenv]($style) "
