_M = {}

-- Generate a lock file with the commit hash of every plugin that is currently
-- installed. Output is written to the current buffer.
function _M.generate_lock_file()
    local lock = {}

    lock[#lock+1] = [[-- Generated by ~/.config/nvim/lua/utilities/packer.lua]]
    lock[#lock+1] = [[local lock = {}]]

    -- Get a sorted list of plugin names.
    local plugin_names = {}
    for name in pairs(packer_plugins) do
        table.insert(plugin_names, name)
    end
    table.sort(plugin_names)

    -- Get the commit hash for each plugin.
    for _, name in ipairs(plugin_names) do
        local plugin = packer_plugins[name]
        local cmd = string.format([[echo -n $(cd "%s" && git rev-parse HEAD)]], plugin.path)
        local commit = vim.fn.system(cmd)

        lock[#lock+1] = string.format([[lock["%s"] = "%s"]], name, commit)
    end

    lock[#lock+1] = [[return lock]]

    -- Write output to the current buffer.
    vim.api.nvim_buf_set_lines(0, 0, -1, false, lock)
end

return _M
