# If not running interactively, don't do anything.
[ -z "$PS1" ] && return

# Update window size.
shopt -s checkwinsize
shopt -s histappend

# https://www.digitalocean.com/community/tutorials/how-to-use-bash-history-commands-and-expansions-on-a-linux-vps
# History Sizes
HISTSIZE=5000
HISTFILESIZE=10000

# Bash specific functions 
export DOTFILES_PATH="${HOME}/code/dotfiles/"
# Bash specific functions
[ -f "$HOME/.bash_functions_colors" ] && . "$HOME/.bash_functions_colors"
[ -f "$HOME/.bash_functions_git" ] && . "$HOME/.bash_functions_git"
[ -f "$HOME/.bash_functions_calendar" ] && . "$HOME/.bash_functions_calendar"
# [ -f "$HOME/.bash_functions_weedmaps" ] && . "$HOME/.bash_functions_weedmaps"
[ -f "$HOME/.bash_functions_filevine" ] && . "$HOME/.bash_functions_filevine"
[ -f "$HOME/.bash_functions_docker" ] && . "$HOME/.bash_functions_docker"
[ -f "$HOME/.bash_functions_awscli" ] && . "$HOME/.bash_functions_awscli"
[ -f "$HOME/.bash_functions_tail" ] && . "$HOME/.bash_functions_tail"
[ -f "$HOME/.bash_functions" ] && . "$HOME/.bash_functions"

#export BUILD_RELEASE_LOCAL_DIR='code/weedmaps/build-release/'
#export BUILD_RELEASE_LOCAL_HELP_DIR="${HOME}/${BUILD_RELEASE_LOCAL_DIR}/command-line-help"
#[ -f "${BUILD_RELEASE_LOCAL_HELP_DIR}/bash_functions_weedmaps" ] && . "${BUILD_RELEASE_LOCAL_HELP_DIR}/bash_functions_weedmaps"
#export CLAPTT_GENERALTEMPLATE='code/wm/claptt_general_template/' # change this to point to your local claptt_general_template repo
export CLAPTT_GENERALTEMPLATE_HELP_DIR="${HOME}/${CLAPTT_GENERALTEMPLATE}/" # You should not have to modify this
# Uncomment the below line in .bashrc to include this file
[ -f "${CLAPTT_GENERALTEMPLATE_HELP_DIR}/bash_functions_help" ] && . "${CLAPTT_GENERALTEMPLATE_HELP_DIR}/bash_functions_help"
# Let's add in the additional files/structures (Copy this into your ~/.bashrc file)
export CLAPTT_ABBY='code/personal_kb/' # change this to point to your local claptt_abby repo
export CLAPTT_ABBY_HELP_DIR="${HOME}/${CLAPTT_ABBY}/" # You should not have to modify this
# Uncomment the below line in .bashrc to include this file
[ -f "${CLAPTT_ABBY_HELP_DIR}/bash_functions_help" ] && . "${CLAPTT_ABBY_HELP_DIR}/bash_functions_help"
# Let's add in the additional files/structures (Copy this into your ~/.bashrc file)
export CLAPTT_BNR='code/wm/claptt_build_and_release/' # change this to point to your local claptt_build_and_release repo
export CLAPTT_BNR_HELP_DIR="${HOME}/${CLAPTT_BNR}/" # You should not have to modify this
# Uncomment the below line in .bashrc to include this file
[ -f "${CLAPTT_BNR_HELP_DIR}/bash_functions_help" ] && . "${CLAPTT_BNR_HELP_DIR}/bash_functions_help"

#export BUILD_RELEASE_LOCAL_DIR='code/weedmaps_code/build-release/' # change this to point to your local build-release repo
#export BUILD_RELEASE_LOCAL_HELP_DIR="${HOME}/${BUILD_RELEASE_LOCAL_DIR}/command-line-help" # You should not have to modify this
[ -f "${BUILD_RELEASE_LOCAL_HELP_DIR}/bash_functions_weedmaps" ] && . "${BUILD_RELEASE_LOCAL_HELP_DIR}/bash_functions_weedmaps"
export CLAPTT_BNR='code/weedmaps_code/claptt_build_and_release/' # change this to point to your local claptt_build_and_release repo
export CLAPTT_BNR_HELP_DIR="${HOME}/${CLAPTT_BNR}/" # You should not have to modify this
# Uncomment the below line in .bashrc to include this file
[ -f "${CLAPTT_BNR_HELP_DIR}/bash_functions_help" ] && . "${CLAPTT_BNR_HELP_DIR}/bash_functions_help"
# Let's add in the additional files/structures (Copy this into your ~/.bashrc file)
export CLAPTT_ABBY='code/claptt_abby/' # change this to point to your local claptt_abby repo
export CLAPTT_ABBY_HELP_DIR="${HOME}/${CLAPTT_ABBY}/" # You should not have to modify this
# Uncomment the below line in .bashrc to include this file
[ -f "${CLAPTT_ABBY_HELP_DIR}/bash_functions_help" ] && . "${CLAPTT_ABBY_HELP_DIR}/bash_functions_help"

#
# PROMPT
#

if [[ "$TERM" =~ .*-256color ]]; then
    icon_commit='➦'
    icon_branch='|>'
    icon_separator=''
else
    icon_commit='c:'
    icon_branch='b:'
    icon_separator=''
fi

PROMPT_COMMAND='set_prompt'

# https://www.digitalocean.com/community/tutorials/how-to-use-bash-history-commands-and-expansions-on-a-linux-vps

# Adding shared history support -- multiple terminals (useful for tmux/screen)
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

#
# ALIASES
#

#PS1=""

# Linux specific setup.
#if [ $(uname) == 'Linux' && 'custom']; then
#  [ -f "$HOME/.bash_aliases_linux_custom" ] && . "$HOME/.bash_aliases_linux_custom"
#fi
if [ $(uname) == 'Linux' ]; then
  [ -f "$HOME/.bash_aliases_linux" ] && . "$HOME/.bash_aliases_linux"
fi
if [ $(uname) == 'CYGWIN_NT-10.0' ]; then
  [ -f "$HOME/.bash_aliases_cygwin" ] && . "$HOME/.bash_aliases_cygwin"
fi

# Mac OS X specific setup.
if [ $(uname) == 'Darwin' ]; then
  [ -f "$HOME/.bash_aliases_darwin" ] && . "$HOME/.bash_aliases_darwin"
fi

#
# SSH
#

# Setup SSH agent.
if [ -n "$SSH_TTY" ]; then
    SSH_ENV=~/.ssh/environment

    function start_agent {
        echo "Initializing new SSH agent..."
        /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
        chmod 600 "${SSH_ENV}"
        . "${SSH_ENV}" > /dev/null
        ssh-add
    }

    # Source SSH settings, if applicable.
    if [ -f "${SSH_ENV}" ]; then
        . "${SSH_ENV}" > /dev/null
        ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
            start_agent
        }
    else
        start_agent
    fi
fi

#
# GIT
#

# Git paging.
export GIT_PAGER='less -+$LESS -FXR'

# Git auto completion.
if [ -n "$BASH_VERSION" ]; then
    . ~/.git-completion.bash
fi

#
# PATHS
#

# ASDF paths
ASDF_GOLANG=1.13
ASDF_NODEJS=13.2.0

#export PATH="~/code/weedmaps_code/weedmaps-tools/git:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/go/bin:~/code/dotfiles/bin:$PATH"
#export PATH="$HOME/.asdf/installs/golang/1.13/bin/:$HOME/.asdf/installs/nodejs/13.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/go/bin:$HOME/code/dotfiles/bin:$PATH"
# export GIT_EXEC_PATH="/usr/libexec/git-core/"
# Add user binary path.
[ -d "$HOME/bin" ] && export PATH="$PATH:$HOME/bin"
# Add RVM to path.
# [ -f "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"

#
# OTHER
#

# Allow server-specific scripting.
[ -f "$HOME/.bash_custom" ] && . "$HOME/.bash_custom"
[ -f "$HOME/.bash_alias" ] && . "$HOME/.bash_alias"

# Bash specific aliases
[ -f "$HOME/.bash_aliases" ] && . "$HOME/.bash_aliases"

# Install asdf - https://asdf-vm.com/#/core-manage-asdf-vm
# This will help you manage versions for ruby, nodejs, elixir, golang
# Don't forget to set global versions
# Usage: 
# asdf plugin-add <plugin> # Example: asdf plugin-add nodejs
# asdf list-all <plugin> # Example: asdf list-all nodejs
# asdf install nodejs 11.14.0
# asdf global nodejs 11.14.0
# 
# Plugins: https://asdf-vm.com/#/plugins-all
# More info: https://blog.patricio.me/installing-and-start-using-asdf-on-macos-high-sierra/

# vim:: set ft=sh

export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:$PATH"
export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"

export PATH="/home/abby/.asdf/installs/golang/1.13/go/bin/:$PATH"

. $HOME/.asdf/asdf.sh
# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/
# export BASH_IT_THEME='bobby'
export BASH_IT_THEME='doubletime_multiline'


# Load Bash It
# source "$BASH_IT"/bash_it.sh
export DOCKER_HOST=tcp://localhost:2375

# Path to the bash it configuration
export BASH_IT="/home/abby/.bash_it"

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
source "$BASH_IT"/bash_it.sh

complete -C /usr/bin/terraform terraform
